config/routes.rb
Rails.application.routes.draw do
    root to: 'homes#top'
    get 'rank'=>'homes#rank'

  namespace :public do
    devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
    resource :users
    resources :recipes, only: [:show, :index] do
        get :search, on: :collection
        resource :favorites, only: [:create, :destroy, :index]
        resources :recipe_comments, only: [:create, :destroy]
    end


    resources :stores , only: [:show] do
      get 'stores_recipe'=>'recipes#stores_recipe'
    end

  end

  namespace :admin do
     resources :recipes
     devise_for :stores, controllers: {
        sessions: 'stores/sessions',
        registrations: 'stores/registrations'
      }
       resources :stores
  end




end

app/models/store.rb
class Store < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes, dependent: :destroy
  attachment :image

end

app/controllers/admin/stores_controller.rb
class  Admin::StoresController < ApplicationController

  def create
    store=Store.new(store_params)
    store.save
    sign_in store
    redirect_to admin_stores_path
  end

  def edit
    @store=current_admin_store
  end

  def update

    @store=current_admin_store
    @store.update(store_params)
    redirect_to  admin_stores_path
  end

  def show
    @store=current_admin_store
  end

  def destroy
    @store=current_admin_store
    @store.destroy
    redirect_to root_path
  end


  private

    def store_params
      params.require(:store).permit(:name, :genre, :area, :station, :url, :phrase, :image, :email, :password, :password_confirmation)
    end

end

app/controllers/stores/confirmations_controller.rb
# frozen_string_literal: true

class Stores::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/stores/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Stores::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/stores/passwords_controller.rb
# frozen_string_literal: true

class Stores::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/stores/registrations_controller.rb
# frozen_string_literal: true

class Stores::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/stores/sessions_controller.rb
# frozen_string_literal: true

class Stores::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/stores/unlocks_controller.rb
# frozen_string_literal: true

class Stores::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/admin/stores/edit.html.erb
<div class="backcolor">
  <h1>お店情報の編集</h1>
  <%= form_with model:@store,url: admin_stores_path(@store), local:true do |t| %>
  <table>
    <tr>
      <th>店名</th>
      <td><%= t.text_field :name %></td></tr>
      <tr><th>ジャンル</th>
      <td><%= t.text_field :genre %></td></tr>
      <tr><th>地域</th>
      <td><%= t.text_field :area %></td></tr>
      <tr><th>最寄り駅</th>
      <td><%= t.text_field :station %></td></tr>
      <tr> <th>URL</th>
      <td><%= t.text_field :url %></td></tr>
     <tr> <th>一言</th>
      <td><%= t.text_area :phrase %></td></tr>
     <tr><th>イメージ写真</th>
      <td><%= t.attachment_field :image %></td></tr>
  <% if  @store=current_admin_store %>
  </table>
  <%= t.submit"更新" %>
  <% end %>
  <%#バリデーションのエラーメッセージ%>
  <%= link_to '退会',admin_store_path, method: :delete, "data-confirm" => "本当に退会しますか？" %>
  <% end %>
</div>

app/views/admin/stores/show.html.erb
<div class="backcolor">
  <h1>お店情報</h1>
  <div class="container">
    <div class="row">
     <div class="col-lg-4" >
              <%= attachment_image_tag @store, :image, :fill,300,200, format:'jpg' %>
      </div>
     <div class="col-lg-8" >
          <table>
              <tr><th>店名</th><td>   <%= @store.name %></td></tr>
              <%#URLを外部リンクにする%>
              <tr><th> url</th><td>  <%= Rinku.auto_link(@store.url, :all, 'target="_blank"').html_safe %></td></tr>
              <tr><th>一言</th><td>  <%= @store.phrase %></td></tr>
              <tr><th>ジャンル</th><td>  <%= @store.genre %></td></tr>
              <tr><th>地域</th><td>   <%= @store.area %></td></tr>
              <tr><th>最寄り駅</th><td>  <%= @store.station %></td></tr>
          </table>
     </div>
    </div>
     <%= link_to "編集",edit_admin_store_path, method: :get %>
</div>
</div>