config/routes.rb
Rails.application.routes.draw do
    root to: 'homes#top'
    get 'rank'=>'homes#rank'

  namespace :public do
    devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
    resource :users
    resources :recipes, only: [:show, :index] do
        get :search, on: :collection
        resource :favorites, only: [:create, :destroy, :index]
        resources :recipe_comments, only: [:create, :destroy]
    end


    resources :stores , only: [:show] do
      get 'stores_recipe'=>'recipes#stores_recipe'
    end

  end

  namespace :admin do
     resources :recipes
     devise_for :stores, controllers: {
        sessions: 'stores/sessions',
        registrations: 'stores/registrations'
      }
       resources :stores
  end




end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @recipes=Recipe.all.page(params[:page]).reverse_order
    @genre = Store.group(:genre).pluck(:genre).sort
    @area = Store.group(:area).pluck(:area).sort
    @station = Store.group(:station).pluck(:station).sort


  end

  def rank
    # binding.irb
    favorite_ids = Favorite.group(:recipe_id).order(Arel.sql('count(recipe_id) desc')).limit(10).pluck(:recipe_id)
    @recipe_favorite_ranks = Recipe.find(favorite_ids)
  end
end

app/views/homes/rank.html.erb
<div class="backcolor">
  <table>
    <tr>
      <th> ランキング</th>
      <th>イメージ</th>
      <th>レシピ名</th>
      <th>何人前</th>
      <th>      </th>

    </tr>
  </table>
  <% @recipe_favorite_ranks.each.with_index(1) do |recipe,i| %>
    <table>
      <tr>
        <th>第<%= i %>位</th>
        <th><%= attachment_image_tag recipe, :image, :fill,200,100, format:'jpg' %></th>
        <th><%= recipe.cooking_name %></th>
        <th><%= recipe.amount %></th>
        <th><%= link_to '詳細',public_recipe_path(recipe) %></th>
      </tr>
    </table>
  <% end %>
</div>

app/views/homes/top.html.erb
<div class="backcolor">
   <div class="search">
<%= form_tag(search_public_recipes_path, method: "get") do %>
 <%= select_tag 'genre', options_for_select(@genre) %>
 <%= select_tag 'area', options_for_select(@area) %>
 <%= select_tag 'station', options_for_select(@station) %>
 <%= submit_tag "絞り込み検索" %>
<% end %>

    <%= form_with url: search_public_recipes_path, method: :get, local: true do |f| %>
    <%= f.text_area :search_word, placeholder: "ジャンル、エリア、最寄り駅で検索"%>
      <%= f.submit "検索" %>
    <% end %>
  </div>
  <div class="rank"><%= link_to 'ランキング!',rank_path %></div>
    <table>
      <tr>
        <th>イメージ</th>
        <th>レシピ名</th>
        <th>何人前</th>
        <th>      </th>
      </tr>
    </table>
  <% @recipes.each do |recipe| %>
    <table>
      <tr>
        <th><%= attachment_image_tag recipe, :image, :fill,200,100, format:'jpg' %></th>
        <th><%= recipe.cooking_name %></th>
        <th><%= recipe.amount %></th>
        <th><%= link_to '詳細',public_recipe_path(recipe) %></th>
      </tr>
    </table>
  <% end %>
  <%= paginate @recipes %>
</div>