config/routes.rb
Rails.application.routes.draw do
    root to: 'homes#top'
    get 'rank'=>'homes#rank'

  namespace :public do
    devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
    resource :users
    resources :recipes, only: [:show, :index] do
        get :search, on: :collection
        resource :favorites, only: [:create, :destroy, :index]
        resources :recipe_comments, only: [:create, :destroy]
    end


    resources :stores , only: [:show] do
      get 'stores_recipe'=>'recipes#stores_recipe'
    end

  end

  namespace :admin do
     resources :recipes
     devise_for :stores, controllers: {
        sessions: 'stores/sessions',
        registrations: 'stores/registrations'
      }
       resources :stores
  end




end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Orenoude</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <h1 class="headline"><a>俺の腕とプロの腕</a></h1>
    <% if admin_store_signed_in? %>
     <ul class="nav-list">
     <li>
        <%= link_to "レシピ投稿", new_admin_recipe_path, method: :get %>
      </li>

      <li>
        <%= link_to "レシピ一覧", admin_recipes_path, method: :get %>
      </li>
       <li>
        <%= link_to "マイページ",admin_store_path(current_admin_store), method: :get %>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_admin_store_session_path, method: :delete %>
      </li>
      <li><%= link_to 'トップページ', root_path %></li>
      <% elsif public_user_signed_in? %>
       <li>
        <%= link_to "ログアウト", destroy_public_user_session_path, method: :delete %>
      </li>
      <li>
        <%= link_to "いいねレシピ",public_recipes_path, method: :get %>
      </li>
      <li><%= link_to 'トップページ', root_path %></li>
    <% else %>
      <li>
        <%= link_to "ユーザー新規登録", new_public_user_registration_path %>
      </li>
      <li>
        <%= link_to "ユーザーログイン", new_public_user_session_path %>
      </li>

      <li>
        <%= link_to "店舗新規登録", new_admin_store_registration_path %>
      </li>
      <li>
        <%= link_to "店舗ログイン", new_admin_store_session_path %>
      </li>
      <li><%= link_to 'トップページ', root_path %></li>
    </ul>
    <% end %>
  </header>
  <body>

    <%= yield %>
  </body>
  <footer>
    orenoude to puronoude.inc
  </footer>
</html>